-- MySQL Script generated by MySQL Workbench
-- mar 08 oct 2024 11:15:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbPIEC
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbPIEC` ;

-- -----------------------------------------------------
-- Schema dbPIEC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbPIEC` ;
USE `dbPIEC` ;

-- -----------------------------------------------------
-- Table `dbPIEC`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`alumnos` (
  `boleta` INT(11) NOT NULL,
  `nombres_Al` VARCHAR(45) NOT NULL,
  `apellidoP_Al` VARCHAR(30) NOT NULL,
  `apellidoM_Al` VARCHAR(30) NULL,
  `correoRec` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`boleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`docentes` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`docentes` (
  `noTrabajador` INT NOT NULL,
  `nombres_Do` VARCHAR(45) NOT NULL,
  `apellidoP_Do` VARCHAR(30) NOT NULL,
  `apellidoM_Do` VARCHAR(30) NULL,
  `correoRec` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`noTrabajador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`materias` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`materias` (
  `idmaterias` INT NOT NULL,
  `material` VARCHAR(70) NULL,
  PRIMARY KEY (`idmaterias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`videos` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`videos` (
  `idvideos` INT NOT NULL,
  `titulo_V` VARCHAR(100) NOT NULL,
  `dirección_V` LONGTEXT NOT NULL,
  `v_boleta` INT(11) NOT NULL,
  `v_idmaterias` INT NOT NULL,
  PRIMARY KEY (`idvideos`, `v_boleta`, `v_idmaterias`),
  INDEX `fk_videos_alumnos1_idx` (`v_boleta` ASC) ,
  INDEX `fk_videos_materias1_idx` (`v_idmaterias` ASC) ,
  CONSTRAINT `fk_videos_alumnos1`
    FOREIGN KEY (`v_boleta`)
    REFERENCES `dbPIEC`.`alumnos` (`boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videos_materias1`
    FOREIGN KEY (`v_idmaterias`)
    REFERENCES `dbPIEC`.`materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`grupos` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`grupos` (
  `g_idmaterias` INT NOT NULL,
  `g_doc_noTrabajador` INT NOT NULL,
  `idgrupos` VARCHAR(6) NOT NULL,
  `fechin` DATETIME NOT NULL,
  `fechfin` DATETIME NOT NULL,
  PRIMARY KEY (`g_idmaterias`, `idgrupos`),
  INDEX `fk_grupos_docentes1_idx` (`g_doc_noTrabajador` ASC) ,
  CONSTRAINT `fk_grupos_materias1`
    FOREIGN KEY (`g_idmaterias`)
    REFERENCES `dbPIEC`.`materias` (`idmaterias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_grupos_docentes1`
    FOREIGN KEY (`g_doc_noTrabajador`)
    REFERENCES `dbPIEC`.`docentes` (`noTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`grabaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`grabaciones` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`grabaciones` (
  `idgrabaciones` INT NOT NULL,
  `dirección_G` LONGTEXT NOT NULL,
  `titulo_G` VARCHAR(100) NOT NULL,
  `g_fecha` DATETIME NOT NULL,
  `gr_idmaterias` INT NOT NULL,
  `gr_idgrupos` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`idgrabaciones`, `gr_idmaterias`, `gr_idgrupos`),
  INDEX `fk_grabaciones_grupos1_idx` (`gr_idmaterias` ASC, `gr_idgrupos` ASC) ,
  CONSTRAINT `fk_grabaciones_grupos1`
    FOREIGN KEY (`gr_idmaterias` , `gr_idgrupos`)
    REFERENCES `dbPIEC`.`grupos` (`g_idmaterias` , `idgrupos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`tareas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`tareas` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`tareas` (
  `idtareas` INT NOT NULL,
  `titulo_T` VARCHAR(255) NOT NULL,
  `descripción_T` LONGTEXT NOT NULL,
  `ta_idmaterias` INT NOT NULL,
  `ta_idgrupos` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`idtareas`),
  INDEX `fk_tareas_grupos1_idx` (`ta_idmaterias` ASC, `ta_idgrupos` ASC) ,
  CONSTRAINT `fk_tareas_grupos1`
    FOREIGN KEY (`ta_idmaterias` , `ta_idgrupos`)
    REFERENCES `dbPIEC`.`grupos` (`g_idmaterias` , `idgrupos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`entregas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`entregas` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`entregas` (
  `e_idtareas` INT NOT NULL,
  `e_idgrupos` VARCHAR(6) NOT NULL,
  `e_boleta` INT(11) NOT NULL,
  `calificación` FLOAT NULL,
  `e_fecha` DATETIME NOT NULL,
  PRIMARY KEY (`e_idtareas`, `e_idgrupos`, `e_boleta`),
  INDEX `fk_tareas_has_alumnos_alumnos1_idx` (`e_boleta` ASC) ,
  INDEX `fk_tareas_has_alumnos_tareas1_idx` (`e_idtareas` ASC, `e_idgrupos` ASC) ,
  CONSTRAINT `fk_tareas_has_alumnos_tareas1`
    FOREIGN KEY (`e_idtareas`)
    REFERENCES `dbPIEC`.`tareas` (`idtareas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_has_alumnos_alumnos1`
    FOREIGN KEY (`e_boleta`)
    REFERENCES `dbPIEC`.`alumnos` (`boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`documentos` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`documentos` (
  `iddocumentos` INT NOT NULL,
  `dircción_D` LONGTEXT NOT NULL,
  `d_idtareas` INT NOT NULL,
  `d_idgrupos` VARCHAR(6) NOT NULL,
  `d_boleta` INT(11) NOT NULL,
  PRIMARY KEY (`iddocumentos`, `d_idtareas`, `d_idgrupos`, `d_boleta`),
  INDEX `fk_documentos_entregas1_idx` (`d_idtareas` ASC, `d_idgrupos` ASC, `d_boleta` ASC) ,
  CONSTRAINT `fk_documentos_entregas1`
    FOREIGN KEY (`d_idtareas` , `d_idgrupos` , `d_boleta`)
    REFERENCES `dbPIEC`.`entregas` (`e_idtareas` , `e_idgrupos` , `e_boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`Comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`Comentarios` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`Comentarios` (
  `idComentarios` INT NOT NULL,
  `Comentario` LONGTEXT NOT NULL,
  `c_idtareas` INT NOT NULL,
  `c_idgrupos` VARCHAR(6) NOT NULL,
  `c_boleta` INT(11) NOT NULL,
  `c_fecha` DATETIME NOT NULL,
  `doc_al` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idComentarios`, `c_idtareas`, `c_idgrupos`, `c_boleta`),
  INDEX `fk_Comentarios_entregas1_idx` (`c_idtareas` ASC, `c_idgrupos` ASC, `c_boleta` ASC) ,
  CONSTRAINT `fk_Comentarios_entregas1`
    FOREIGN KEY (`c_idtareas` , `c_idgrupos` , `c_boleta`)
    REFERENCES `dbPIEC`.`entregas` (`e_idtareas` , `e_idgrupos` , `e_boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`avisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`avisos` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`avisos` (
  `idAviso` INT NOT NULL,
  `aviso` LONGTEXT NOT NULL,
  `a_fecha` DATETIME NOT NULL,
  `av_idmaterias` INT NOT NULL,
  `av_idgrupos` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`idAviso`, `av_idmaterias`, `av_idgrupos`),
  INDEX `fk_avisos_grupos1_idx` (`av_idmaterias` ASC, `av_idgrupos` ASC) ,
  CONSTRAINT `fk_avisos_grupos1`
    FOREIGN KEY (`av_idmaterias` , `av_idgrupos`)
    REFERENCES `dbPIEC`.`grupos` (`g_idmaterias` , `idgrupos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`horarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`horarios` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`horarios` (
  `Horarios` INT NOT NULL,
  `dia` VARCHAR(11) NOT NULL,
  `entrada` TIME NOT NULL,
  `salida` TIME NOT NULL,
  `ho_idmaterias` INT NOT NULL,
  `ho_idgrupos` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`Horarios`, `ho_idmaterias`, `ho_idgrupos`),
  INDEX `fk_horarios_grupos1_idx` (`ho_idmaterias` ASC, `ho_idgrupos` ASC) ,
  CONSTRAINT `fk_horarios_grupos1`
    FOREIGN KEY (`ho_idmaterias` , `ho_idgrupos`)
    REFERENCES `dbPIEC`.`grupos` (`g_idmaterias` , `idgrupos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPIEC`.`grupos_alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbPIEC`.`grupos_alumnos` ;

CREATE TABLE IF NOT EXISTS `dbPIEC`.`grupos_alumnos` (
  `ga_idmaterias` INT NOT NULL,
  `ga_idgrupos` VARCHAR(6) NOT NULL,
  `ga_boleta` INT(11) NOT NULL,
  PRIMARY KEY (`ga_idmaterias`, `ga_idgrupos`, `ga_boleta`),
  INDEX `fk_grupos_has_alumnos_alumnos1_idx` (`ga_boleta` ASC) ,
  INDEX `fk_grupos_has_alumnos_grupos1_idx` (`ga_idmaterias` ASC, `ga_idgrupos` ASC) ,
  CONSTRAINT `fk_grupos_has_alumnos_grupos1`
    FOREIGN KEY (`ga_idmaterias` , `ga_idgrupos`)
    REFERENCES `dbPIEC`.`grupos` (`g_idmaterias` , `idgrupos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_has_alumnos_alumnos1`
    FOREIGN KEY (`ga_boleta`)
    REFERENCES `dbPIEC`.`alumnos` (`boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
